name: rule1
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - pandas=1.3.4
  - pip:
    - azureml-sdk==1.40.0
    - azure-storage-file-datalake==12.6.0
    - azure-identity==1.7.0
    - GitPython==3.1.27
    - ipykernel
    - nb_conda_kernels